### PR TITLE
Back up seed

### PR DESCRIPTION
**Pull request by bapisit**
Hello there how do i recover seed or 12 word

### CODE REVIEW

**Comment by bapisit** [comment]
I lost all keyfiles how do i backup mnemonic-phrase

**Comment by sisou** [comment]
Hello @bapisit,

When you created your account, you where shown your 24 recovery words. If you have your accounts in the Safe, you can get your words by clicking on the menu in the account window and selecting 'Export Recovery Words'.

**Comment by bapisit** [comment]
yes am in safe place please provide me Recovery words

**Comment by sisou** [comment]
In the Safe, click on your account in the account list:
screenshot from 2018-09-06 12-48-06

Then click on the menu button in the top left:
screenshot from 2018-09-06 12-48-26

Then click on "Backup Recovery Words":
screenshot from 2018-09-06 12-48-42

Then follow the instructions, enter you passphrase, and you will see your words.

**Comment by bapisit** [comment]
hello tell about this after backup my 24 words how to recover wallet or coins

**Comment by sisou** [comment]
Hello @bapisit!

Please go to https://safe.nimiq.com and if you see this menu, click on **Login**:
image

If you do not see this menu immediately, click on "Add Account" to go to the above menu here:
image

In the next screen, click on "Login with Recovery Words":
image

Then enter your words in the numbered fields:
image

**Comment by bapisit** [comment]
Okay i have backup my wallet but i see confirmation process taking place in
safe.nimiq.com ,does my 24 words connecting all coin eg BTC ETHER etc) i
see only MIN

**Comment by sisou** [comment]
@bapisit 
The Nimiq Safe at safe.nimiq.com is only for NIM.

**Comment by bapisit** [comment]
Okay meaning does my 24 words connecting all after recovering with ledger

**Comment by sisou** [comment]
I don't really understand what you mean.

If the 24 Recovery Words are from a Ledger, you can use a new Ledger and recover it like so: https://support.ledger.com/hc/en-us/articles/360005434914-Restore-from-recovery-phrase

If you want to access your BTC/ETH/BTH that you had on your Ledger, but don't have a working Ledger, you can use a supporting app from those currencies to recover your accounts. Please ask in the respective forums, reddit or google for help with those currencies.

**Comment by bapisit** [comment]
I was saying that what if i want to access BTC or ETH etc from my 24 words
,does my 24 words connecting all min? Or etc

**Pull request closed without merging**
